/**
 * Generates responsive derivatives for everything under public/images (plus a
 * couple of loose files) and writes a manifest the components read at build
 * time.
 *
 * The site is a static export on GitHub Pages, so `next/image` is off
 * (`images: { unoptimized: true }`) and nothing resizes on the fly — without
 * this step a post ships the original 3 MB scan to every visitor. Derivatives
 * land in public/_img (gitignored, regenerated by prebuild/predev) and the
 * manifest in .image-manifest.json at the repo root.
 *
 * Re-running is cheap: an entry is reused when the source's mtime and size
 * are unchanged.
 */
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const ROOT = process.cwd();
const PUBLIC = path.join(ROOT, 'public');
const OUT_DIR = path.join(PUBLIC, '_img');
const MANIFEST = path.join(ROOT, '.image-manifest.json');

/** Directories under public/ scanned recursively, plus individual files. */
const SCAN_DIRS = ['images'];
const SCAN_FILES = ['jesterbw.webp', 'home-image.png'];

const SOURCE_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp']);

/**
 * Rendered widths on this site top out around 780 CSS px (the 65ch reading
 * column) and the lightbox at ~95vw, so 1800 covers a 2x retina lightbox and
 * anything wider is wasted bytes.
 */
const WIDTHS = [400, 800, 1200, 1800];
const WEBP = { quality: 78, effort: 5 };
/** Inlined as a background-image so the box is never blank while loading. */
const BLUR_WIDTH = 20;

function walk(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return full === OUT_DIR ? [] : walk(full);
    return SOURCE_EXT.has(path.extname(entry.name).toLowerCase()) ? [full] : [];
  });
}

/** public/images/a/b.png -> /images/a/b.png (the URL posts actually use). */
function toUrl(absolute) {
  return '/' + path.relative(PUBLIC, absolute).split(path.sep).join('/');
}

/** Encoded the same way lib/images.ts and the MDX sources write their srcs. */
function encodeUrl(url) {
  return url.split('/').map(encodeURIComponent).join('/');
}

const previous = fs.existsSync(MANIFEST)
  ? JSON.parse(fs.readFileSync(MANIFEST, 'utf8'))
  : {};

const sources = [
  ...SCAN_DIRS.flatMap((dir) => walk(path.join(PUBLIC, dir))),
  ...SCAN_FILES.map((file) => path.join(PUBLIC, file)).filter((file) =>
    fs.existsSync(file)
  ),
];

const manifest = {};
let generated = 0;
let reused = 0;
let sourceBytes = 0;
let derivedBytes = 0;

for (const source of sources) {
  const url = toUrl(source);
  const stat = fs.statSync(source);
  sourceBytes += stat.size;

  const cached = previous[url];
  const fingerprint = `${stat.size}:${Math.round(stat.mtimeMs)}`;
  const cacheHit =
    cached?.fingerprint === fingerprint &&
    cached.variants.every((variant) =>
      fs.existsSync(path.join(PUBLIC, decodeURI(variant.url)))
    );

  if (cacheHit) {
    manifest[url] = cached;
    reused += 1;
    derivedBytes += cached.variants.reduce(
      (total, variant) =>
        total + fs.statSync(path.join(PUBLIC, decodeURI(variant.url))).size,
      0
    );
    continue;
  }

  const image = sharp(source, { failOn: 'none' });
  const meta = await image.metadata();
  if (!meta.width || !meta.height) {
    console.warn(`  ! skipped (no dimensions): ${url}`);
    continue;
  }

  // Never upscale: keep the ladder entries below the source width, then cap
  // the top rung at the source itself so there is always at least one.
  const targets = WIDTHS.filter((width) => width < meta.width);
  targets.push(Math.min(meta.width, WIDTHS[WIDTHS.length - 1]));

  const relativeDir = path.dirname(path.relative(PUBLIC, source));
  const base = path.basename(source, path.extname(source));
  const outDir = path.join(OUT_DIR, relativeDir);
  fs.mkdirSync(outDir, { recursive: true });

  const variants = [];
  for (const width of [...new Set(targets)].sort((a, b) => a - b)) {
    const file = path.join(outDir, `${base}-${width}.webp`);
    await sharp(source, { failOn: 'none' })
      .rotate()
      .resize({ width, withoutEnlargement: true })
      .webp(WEBP)
      .toFile(file);
    derivedBytes += fs.statSync(file).size;
    variants.push({ width, url: encodeUrl(toUrl(file)) });
  }

  const blur = await sharp(source, { failOn: 'none' })
    .rotate()
    .resize({ width: BLUR_WIDTH })
    .webp({ quality: 40, alphaQuality: 60 })
    .toBuffer();

  manifest[url] = {
    fingerprint,
    width: meta.width,
    height: meta.height,
    blur: `data:image/webp;base64,${blur.toString('base64')}`,
    variants,
  };
  generated += 1;
  console.log(`  + ${url} (${variants.map((v) => v.width).join(', ')})`);
}

// Drop derivatives whose source is gone, so the folder can't grow forever.
if (fs.existsSync(OUT_DIR)) {
  const live = new Set(
    Object.values(manifest).flatMap((entry) =>
      entry.variants.map((variant) => path.join(PUBLIC, decodeURI(variant.url)))
    )
  );
  for (const file of walk(OUT_DIR)) {
    if (!live.has(file)) fs.rmSync(file);
  }
}

fs.writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2) + '\n');

const mb = (bytes) => (bytes / 1024 / 1024).toFixed(1) + ' MB';
console.log(
  `images: ${generated} generated, ${reused} reused — ` +
    `${mb(sourceBytes)} of originals -> ${mb(derivedBytes)} of derivatives`
);
